# Generated by Django 3.1.7 on 2021-03-18 08:23

import activity.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20210318_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='photo',
            field=models.FileField(null=True, upload_to='', validators=[activity.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Cancelada'), ('D', 'Finalizada')], max_length=20),
        ),
    ]
