# Generated by Django 3.1.7 on 2021-03-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20210320_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Cancelada'), ('D', 'Finalizada')], default='P', max_length=20),
        ),
    ]
