# Generated by Django 3.1.7 on 2021-04-19 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210419_1723'),
        ('activity', '0006_auto_20210406_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.organizer'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='organized_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.organization'),
        ),
    ]
