# Generated by Django 3.1.7 on 2021-04-22 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_favorites'),
        ('activity', '0007_auto_20210419_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('start_time', models.TimeField(default=datetime.datetime.now)),
                ('activity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='activity.activity')),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user.client')),
            ],
            options={
                'unique_together': {('activity', 'client')},
            },
        ),
    ]
