# Generated by Django 3.1.7 on 2021-05-01 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210501_1500'),
        ('activity', '0007_auto_20210419_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.client')),
            ],
            options={
                'unique_together': {('client', 'activity')},
            },
        ),
    ]
