# Generated by Django 3.1.7 on 2021-05-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210501_1500'),
        ('activity', '0008_favoriteactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteactivity',
            options={'verbose_name_plural': 'Favorite Activities'},
        ),
        migrations.AlterField(
            model_name='favoriteactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity'),
        ),
        migrations.AlterField(
            model_name='favoriteactivity',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client'),
        ),
        migrations.AlterField(
            model_name='instructedby',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activity.activity'),
        ),
        migrations.AlterField(
            model_name='instructedby',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.organizer'),
        ),
    ]
