# Generated by Django 3.1.7 on 2021-05-01 13:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0008_favoriteactivity'),
        ('user', '0005_auto_20210501_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityJoined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('checked_in', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client')),
            ],
            options={
                'unique_together': {('activity', 'client')},
            },
        ),
    ]
