# Generated by Django 3.1.7 on 2021-05-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_action', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityjoined',
            options={'verbose_name_plural': 'Joined Activities'},
        ),
    ]
