# Generated by Django 3.1.7 on 2021-05-04 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_action', '0002_auto_20210501_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('joined', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='activity_action.activityjoined')),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
