# Generated by Django 3.1.7 on 2021-05-08 14:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_action', '0005_auto_20210508_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReview',
            fields=[
                ('joined', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='activity_action.activityjoined')),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('stars', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AlterModelOptions(
            name='activityjoined',
            options={'verbose_name_plural': 'Activity Joined'},
        ),
    ]
