# Generated by Django 3.1.7 on 2021-05-29 12:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_organization_super_host'),
        ('activity_action', '0007_auto_20210511_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreview',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, verbose_name='commentarios'),
        ),
        migrations.AlterField(
            model_name='activityreview',
            name='stars',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='puntuación'),
        ),
        migrations.CreateModel(
            name='ReportActivityReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='activity_action.activityreview')),
            ],
            options={
                'unique_together': {('review', 'client')},
            },
        ),
    ]
