# Generated by Django 3.1.7 on 2021-04-21 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210419_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
