# Generated by Django 3.1.7 on 2021-04-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210421_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='token',
            new_name='token_verification',
        ),
    ]
