# Generated by Django 3.1.7 on 2021-05-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.organization')),
            ],
            options={
                'unique_together': {('organization', 'client')},
            },
        ),
    ]
